In [84]:
#importing necessary libraries
import numpy as np
import pandas as pd

In [85]:
#importing the dataset
df = pd.read_csv("nba_2013.csv")

In [86]:
df.head(2)

,player,pos,age,bref_team_id,g,gs,mp,fg,fga,fg.,...,drb,trb,ast,stl,blk,tov,pf,pts,season,season_end
0,Quincy Acy,SF,23,TOT,63,0,847,66,141,0.468,...,144,216,28,23,26,30,122,171,2013-2014,2013
1,Steven Adams,C,20,OKC,81,20,1197,93,185,0.503,...,190,332,43,40,57,71,203,265,2013-2014,2013

In [87]:
from sklearn.preprocessing import Imputer
from sklearn.cross_validation import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import accuracy_score

In [88]:
#checking shape
df.shape

(481, 31)

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 481 entries, 0 to 480
Data columns (total 31 columns):
player          481 non-null object
pos             481 non-null object
age             481 non-null int64
bref_team_id    481 non-null object
g               481 non-null int64
gs              481 non-null int64
mp              481 non-null int64
fg              481 non-null int64
fga             481 non-null int64
fg.             479 non-null float64
x3p             481 non-null int64
x3pa            481 non-null int64
x3p.            414 non-null float64
x2p             481 non-null int64
x2pa            481 non-null int64
x2p.            478 non-null float64
efg.            479 non-null float64
ft              481 non-null int64
fta             481 non-null int64
ft.             461 non-null float64
orb             481 non-null int64
drb             481 non-null int64
trb             481 non-null int64
ast             481 non-null int64
stl             481 non-null int64
blk             481 non-null int64
tov             481 non-null int64
pf              481 non-null int64
pts             481 non-null int64
season          481 non-null object
season_end      481 non-null int64
dtypes: float64(5), int64(22), object(4)
memory usage: 116.6+ KB

In [90]:
df.describe()

,age,g,gs,mp,fg,fga,fg.,x3p,x3pa,x3p.,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,season_end
count,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,479.000000,481.000000,481.000000,414.000000,...,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.000000,481.0
mean,26.509356,53.253638,25.571726,1237.386694,192.881497,424.463617,0.436436,39.613306,110.130977,0.285111,...,55.810811,162.817048,218.627859,112.536383,39.280665,24.103950,71.862786,105.869023,516.582121,2013.0
std,4.198265,25.322711,29.658465,897.258840,171.832793,368.850833,0.098672,50.855639,132.751732,0.157633,...,62.101191,145.348116,200.356507,131.019557,34.783590,30.875381,62.701690,71.213627,470.422228,0.0
min,19.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2013.0
25%,23.000000,32.000000,0.000000,388.000000,47.000000,110.000000,0.400500,0.000000,3.000000,0.234355,...,12.000000,43.000000,55.000000,20.000000,9.000000,4.000000,21.000000,44.000000,115.000000,2013.0
50%,26.000000,61.000000,10.000000,1141.000000,146.000000,332.000000,0.438000,16.000000,48.000000,0.330976,...,35.000000,135.000000,168.000000,65.000000,32.000000,14.000000,58.000000,104.000000,401.000000,2013.0
75%,29.000000,76.000000,54.000000,2016.000000,307.000000,672.000000,0.479500,68.000000,193.000000,0.375000,...,73.000000,230.000000,310.000000,152.000000,60.000000,32.000000,108.000000,158.000000,821.000000,2013.0
max,39.000000,83.000000,82.000000,3122.000000,849.000000,1688.000000,1.000000,261.000000,615.000000,1.000000,...,440.000000,783.000000,1114.000000,721.000000,191.000000,219.000000,295.000000,273.000000,2593.000000,2013.0

In [91]:
print(df.columns)
print(len(df.columns))
#there are 31 columns

Index(['player', 'pos', 'age', 'bref_team_id', 'g', 'gs', 'mp', 'fg', 'fga',
       'fg.', 'x3p', 'x3pa', 'x3p.', 'x2p', 'x2pa', 'x2p.', 'efg.', 'ft',
       'fta', 'ft.', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf',
       'pts', 'season', 'season_end'],
      dtype='object')
31

In [92]:
#columns to drop
#player- player name has no effect on no of points scored
#columns for which we have to create dummy are pos, bref_team_id,season
df.isnull().sum()

player           0
pos              0
age              0
bref_team_id     0
g                0
gs               0
mp               0
fg               0
fga              0
fg.              2
x3p              0
x3pa             0
x3p.            67
x2p              0
x2pa             0
x2p.             3
efg.             2
ft               0
fta              0
ft.             20
orb              0
drb              0
trb              0
ast              0
stl              0
blk              0
tov              0
pf               0
pts              0
season           0
season_end       0
dtype: int64

In [93]:
#dropping the columns which have no impact
new_df = df.drop(columns=["player","season_end","season"])

In [94]:
new_df.head()

,pos,age,bref_team_id,g,gs,mp,fg,fga,fg.,x3p,...,ft.,orb,drb,trb,ast,stl,blk,tov,pf,pts
0,SF,23,TOT,63,0,847,66,141,0.468,4,...,0.660,72,144,216,28,23,26,30,122,171
1,C,20,OKC,81,20,1197,93,185,0.503,0,...,0.581,142,190,332,43,40,57,71,203,265
2,PF,27,TOT,53,12,961,143,275,0.520,0,...,0.639,102,204,306,38,24,36,39,108,362
3,SG,28,ORL,73,73,2552,464,1011,0.459,128,...,0.815,32,230,262,248,35,3,146,136,1330
4,C,25,NOP,56,30,951,136,249,0.546,0,...,0.836,94,183,277,40,23,46,63,187,328

In [95]:
nominal_columns = ["pos","bref_team_id"]

In [96]:
#creating dummy variables from the nominal columns
dummy_df = pd.get_dummies(new_df[nominal_columns])

In [97]:
dummy_df

,pos_C,pos_F,pos_G,pos_PF,pos_PG,pos_SF,pos_SG,bref_team_id_ATL,bref_team_id_BOS,bref_team_id_BRK,...,bref_team_id_ORL,bref_team_id_PHI,bref_team_id_PHO,bref_team_id_POR,bref_team_id_SAC,bref_team_id_SAS,bref_team_id_TOR,bref_team_id_TOT,bref_team_id_UTA,bref_team_id_WAS
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
7,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
8,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
12,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
15,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
19,0,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
21,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
25,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
27,0,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
452,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
453,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
454,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
455,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
456,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
457,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
458,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
459,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
460,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
461,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
462,0,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
463,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
464,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
465,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
466,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
467,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
468,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
469,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
470,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
471,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
472,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
473,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
474,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
475,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
476,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
477,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
478,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
479,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
480,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [109]:
#joining dummy columns and original data 
ml_df = pd.concat([new_df,dummy_df], axis=1)

In [99]:
#dropping nominal columns that we have converted to dummy data
ml_df.drop(nominal_columns,axis=1,inplace=True)

In [100]:
ml_df.head()

,age,g,gs,mp,fg,fga,fg.,x3p,x3pa,x3p.,...,bref_team_id_ORL,bref_team_id_PHI,bref_team_id_PHO,bref_team_id_POR,bref_team_id_SAC,bref_team_id_SAS,bref_team_id_TOR,bref_team_id_TOT,bref_team_id_UTA,bref_team_id_WAS
0,23,63,0,847,66,141,0.468,4,15,0.266667,...,0,0,0,0,0,0,0,1,0,0
1,20,81,20,1197,93,185,0.503,0,0,NaN,...,0,0,0,0,0,0,0,0,0,0
2,27,53,12,961,143,275,0.520,0,0,NaN,...,0,0,0,0,0,0,0,1,0,0
3,28,73,73,2552,464,1011,0.459,128,300,0.426667,...,1,0,0,0,0,0,0,0,0,0
4,25,56,30,951,136,249,0.546,0,1,0.000000,...,0,0,0,0,0,0,0,0,0,0

In [101]:
#filling missing values with mean
ml_df.fillna(ml_df.mean(), inplace = True)

In [102]:
#checking missing values
ml_df.isna().sum()

age                 0
g                   0
gs                  0
mp                  0
fg                  0
fga                 0
fg.                 0
x3p                 0
x3pa                0
x3p.                0
x2p                 0
x2pa                0
x2p.                0
efg.                0
ft                  0
fta                 0
ft.                 0
orb                 0
drb                 0
trb                 0
ast                 0
stl                 0
blk                 0
tov                 0
pf                  0
pts                 0
pos_C               0
pos_F               0
pos_G               0
pos_PF              0
                   ..
bref_team_id_BOS    0
bref_team_id_BRK    0
bref_team_id_CHA    0
bref_team_id_CHI    0
bref_team_id_CLE    0
bref_team_id_DAL    0
bref_team_id_DEN    0
bref_team_id_DET    0
bref_team_id_GSW    0
bref_team_id_HOU    0
bref_team_id_IND    0
bref_team_id_LAC    0
bref_team_id_LAL    0
bref_team_id_MEM    0
bref_team_id_MIA    0
bref_team_id_MIL    0
bref_team_id_MIN    0
bref_team_id_NOP    0
bref_team_id_NYK    0
bref_team_id_OKC    0
bref_team_id_ORL    0
bref_team_id_PHI    0
bref_team_id_PHO    0
bref_team_id_POR    0
bref_team_id_SAC    0
bref_team_id_SAS    0
bref_team_id_TOR    0
bref_team_id_TOT    0
bref_team_id_UTA    0
bref_team_id_WAS    0
Length: 64, dtype: int64

In [103]:
ml_df.columns

Index(['age', 'g', 'gs', 'mp', 'fg', 'fga', 'fg.', 'x3p', 'x3pa', 'x3p.',
       'x2p', 'x2pa', 'x2p.', 'efg.', 'ft', 'fta', 'ft.', 'orb', 'drb', 'trb',
       'ast', 'stl', 'blk', 'tov', 'pf', 'pts', 'pos_C', 'pos_F', 'pos_G',
       'pos_PF', 'pos_PG', 'pos_SF', 'pos_SG', 'bref_team_id_ATL',
       'bref_team_id_BOS', 'bref_team_id_BRK', 'bref_team_id_CHA',
       'bref_team_id_CHI', 'bref_team_id_CLE', 'bref_team_id_DAL',
       'bref_team_id_DEN', 'bref_team_id_DET', 'bref_team_id_GSW',
       'bref_team_id_HOU', 'bref_team_id_IND', 'bref_team_id_LAC',
       'bref_team_id_LAL', 'bref_team_id_MEM', 'bref_team_id_MIA',
       'bref_team_id_MIL', 'bref_team_id_MIN', 'bref_team_id_NOP',
       'bref_team_id_NYK', 'bref_team_id_OKC', 'bref_team_id_ORL',
       'bref_team_id_PHI', 'bref_team_id_PHO', 'bref_team_id_POR',
       'bref_team_id_SAC', 'bref_team_id_SAS', 'bref_team_id_TOR',
       'bref_team_id_TOT', 'bref_team_id_UTA', 'bref_team_id_WAS'],
      dtype='object')

In [104]:
#dividing the data into features and labels 
X = ml_df[['age', 'g', 'gs', 'mp', 'fg', 'fga', 'fg.', 'x3p', 'x3pa', 'x3p.',
       'x2p', 'x2pa', 'x2p.', 'efg.', 'ft', 'fta', 'ft.', 'orb', 'drb', 'trb',
       'ast', 'stl', 'blk', 'tov', 'pf', 'pos_C', 'pos_F', 'pos_G',
       'pos_PF', 'pos_PG', 'pos_SF', 'pos_SG', 'bref_team_id_ATL',
       'bref_team_id_BOS', 'bref_team_id_BRK', 'bref_team_id_CHA',
       'bref_team_id_CHI', 'bref_team_id_CLE', 'bref_team_id_DAL',
       'bref_team_id_DEN', 'bref_team_id_DET', 'bref_team_id_GSW',
       'bref_team_id_HOU', 'bref_team_id_IND', 'bref_team_id_LAC',
       'bref_team_id_LAL', 'bref_team_id_MEM', 'bref_team_id_MIA',
       'bref_team_id_MIL', 'bref_team_id_MIN', 'bref_team_id_NOP',
       'bref_team_id_NYK', 'bref_team_id_OKC', 'bref_team_id_ORL',
       'bref_team_id_PHI', 'bref_team_id_PHO', 'bref_team_id_POR',
       'bref_team_id_SAC', 'bref_team_id_SAS', 'bref_team_id_TOR',
       'bref_team_id_TOT', 'bref_team_id_UTA', 'bref_team_id_WAS']]
Y= ml_df["pts"]

In [108]:
#didvind the data in to train and test
X_train, X_test, y_train, y_test = train_test_split(
 X, Y, test_size = 0.3, random_state = 100)

In [106]:
#fitting the model finding the accuracy
for K in range(25):
    K_value = K+1
    neigh = KNeighborsRegressor(n_neighbors = K_value, weights='uniform', algorithm='auto')
    neigh.fit(X_train, y_train) 
    y_pred = neigh.predict(X_test)
    #print("neigh.score(X_test,y_test)")
    print("Accuracy is ",neigh.score(X_test,y_test) ," for K-Value:",K_value)

Accuracy is  0.95684731941855  for K-Value: 1
Accuracy is  0.9581492224341541  for K-Value: 2
Accuracy is  0.9624372010810966  for K-Value: 3
Accuracy is  0.9657047491133575  for K-Value: 4
Accuracy is  0.9685320484955778  for K-Value: 5
Accuracy is  0.9679874388567071  for K-Value: 6
Accuracy is  0.9682448535639541  for K-Value: 7
Accuracy is  0.9671430132035298  for K-Value: 8
Accuracy is  0.9663507168096759  for K-Value: 9
Accuracy is  0.9668298403837711  for K-Value: 10
Accuracy is  0.9641896227767904  for K-Value: 11
Accuracy is  0.9607555638247275  for K-Value: 12
Accuracy is  0.9577572790220473  for K-Value: 13
Accuracy is  0.9563258309796986  for K-Value: 14
Accuracy is  0.9562091951366896  for K-Value: 15
Accuracy is  0.9554495593695437  for K-Value: 16
Accuracy is  0.9549112796450947  for K-Value: 17
Accuracy is  0.9532624061612192  for K-Value: 18
Accuracy is  0.9532643557653248  for K-Value: 19
Accuracy is  0.9522271248667119  for K-Value: 20
Accuracy is  0.9511001872209638  for K-Value: 21
Accuracy is  0.949876248787201  for K-Value: 22
Accuracy is  0.9478854074107476  for K-Value: 23
Accuracy is  0.9458164524943505  for K-Value: 24
Accuracy is  0.9439691878555027  for K-Value: 25

### Trying linear regression just for practice

In [72]:
X = ml_df[['age', 'g', 'gs', 'mp', 'fg', 'fga', 'fg.', 'x3p', 'x3pa', 'x3p.',
       'x2p', 'x2pa', 'x2p.', 'efg.', 'ft', 'fta', 'ft.', 'orb', 'drb', 'trb',
       'ast', 'stl', 'blk', 'tov', 'pf', 'pos_C', 'pos_F', 'pos_G',
       'pos_PF', 'pos_PG', 'pos_SF', 'pos_SG', 'bref_team_id_ATL',
       'bref_team_id_BOS', 'bref_team_id_BRK', 'bref_team_id_CHA',
       'bref_team_id_CHI', 'bref_team_id_CLE', 'bref_team_id_DAL',
       'bref_team_id_DEN', 'bref_team_id_DET', 'bref_team_id_GSW',
       'bref_team_id_HOU', 'bref_team_id_IND', 'bref_team_id_LAC',
       'bref_team_id_LAL', 'bref_team_id_MEM', 'bref_team_id_MIA',
       'bref_team_id_MIL', 'bref_team_id_MIN', 'bref_team_id_NOP',
       'bref_team_id_NYK', 'bref_team_id_OKC', 'bref_team_id_ORL',
       'bref_team_id_PHI', 'bref_team_id_PHO', 'bref_team_id_POR',
       'bref_team_id_SAC', 'bref_team_id_SAS', 'bref_team_id_TOR',
       'bref_team_id_TOT', 'bref_team_id_UTA', 'bref_team_id_WAS']]
Y= ml_df["pts"]

In [73]:
X["intercept"] = 1

C:\Users\vishal sangwan\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [74]:
X

,age,g,gs,mp,fg,fga,fg.,x3p,x3pa,x3p.,...,bref_team_id_PHI,bref_team_id_PHO,bref_team_id_POR,bref_team_id_SAC,bref_team_id_SAS,bref_team_id_TOR,bref_team_id_TOT,bref_team_id_UTA,bref_team_id_WAS,intercept
0,23,63,0,847,66,141,0.468,4,15,0.266667,...,0,0,0,0,0,0,1,0,0,1
1,20,81,20,1197,93,185,0.503,0,0,0.285111,...,0,0,0,0,0,0,0,0,0,1
2,27,53,12,961,143,275,0.520,0,0,0.285111,...,0,0,0,0,0,0,1,0,0,1
3,28,73,73,2552,464,1011,0.459,128,300,0.426667,...,0,0,0,0,0,0,0,0,0,1
4,25,56,30,951,136,249,0.546,0,1,0.000000,...,0,0,0,0,0,0,0,0,0,1
5,25,46,2,330,33,61,0.541,0,0,0.285111,...,0,0,0,0,0,0,0,0,0,1
6,28,69,69,2498,652,1423,0.458,3,15,0.200000,...,0,0,1,0,0,0,0,0,0,1
7,24,65,2,1072,134,300,0.447,2,13,0.153846,...,0,0,0,0,0,0,1,0,0,1
8,38,73,9,1936,240,543,0.442,116,309,0.375405,...,0,0,0,0,0,0,0,0,0,1
9,32,55,28,1278,204,413,0.494,11,47,0.234043,...,0,0,0,0,0,0,0,0,0,1
10,23,80,65,2045,234,494,0.474,13,48,0.270833,...,0,0,0,0,0,0,0,0,0,1
11,31,19,0,185,16,32,0.500,0,0,0.285111,...,0,0,0,0,0,0,1,0,0,1
12,35,72,0,1396,177,275,0.644,3,12,0.250000,...,0,0,0,0,0,0,0,0,0,1
13,31,78,26,1773,194,485,0.400,84,248,0.338710,...,0,0,0,0,0,0,0,0,0,1
14,24,80,62,2309,309,717,0.431,115,351,0.327635,...,1,0,0,0,0,0,0,0,0,1
15,25,22,14,795,155,354,0.438,67,164,0.408537,...,0,0,0,0,0,0,0,0,0,1
16,19,77,23,1897,173,418,0.414,41,118,0.347458,...,0,0,0,0,0,0,0,0,0,1
17,29,77,77,2982,743,1643,0.452,167,415,0.402410,...,0,0,0,0,0,0,0,0,0,1
18,31,33,0,186,12,32,0.375,0,0,0.285111,...,0,0,0,0,0,0,1,0,0,1
19,31,50,26,925,123,294,0.418,56,171,0.327485,...,0,0,0,0,0,0,0,0,0,1
20,28,77,77,2723,389,853,0.456,180,442,0.407240,...,0,0,0,0,0,0,0,0,1,1
21,29,15,1,97,9,19,0.474,0,0,0.285111,...,0,0,0,0,0,0,0,0,0,1
22,25,68,1,1161,162,410,0.395,24,64,0.375000,...,0,0,0,0,0,0,0,0,0,1
23,27,48,19,968,101,190,0.532,0,0,0.285111,...,0,0,0,0,0,0,0,0,0,1
24,26,71,9,1939,298,718,0.415,133,332,0.400602,...,0,0,0,0,0,0,1,0,0,1
25,28,26,14,429,52,102,0.510,0,0,0.285111,...,0,0,0,0,0,0,0,0,0,1
26,26,73,10,952,101,174,0.580,0,0,0.285111,...,0,0,0,0,1,0,0,0,0,1
27,23,14,0,132,8,30,0.267,6,27,0.222222,...,0,0,0,0,0,0,0,0,0,1
28,24,27,2,473,60,154,0.390,36,95,0.378947,...,0,0,0,0,0,0,0,0,0,1
29,31,20,0,368,56,131,0.427,7,25,0.280000,...,0,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,23,82,82,2980,579,1337,0.433,108,308,0.350649,...,0,0,0,0,0,0,0,0,1,1
452,31,58,16,1416,116,230,0.504,19,64,0.296875,...,0,0,0,0,0,0,0,0,0,1
453,24,9,0,116,18,42,0.429,7,21,0.333333,...,1,0,0,0,0,0,0,0,0,1
454,29,63,5,1193,146,334,0.437,53,145,0.365517,...,0,0,0,0,0,0,0,0,0,1
455,34,24,0,161,3,11,0.273,2,7,0.285714,...,0,0,1,0,0,0,0,0,0,1
456,22,2,0,9,1,2,0.500,0,0,0.285111,...,0,0,0,0,0,0,0,0,0,1
457,27,78,13,2157,254,587,0.433,146,372,0.392473,...,0,0,0,0,0,0,0,0,1,1
458,33,80,80,2472,458,939,0.488,4,15,0.266667,...,0,0,0,0,0,0,0,0,0,1
459,25,46,46,1412,346,791,0.437,68,214,0.317757,...,0,0,0,0,0,0,0,0,0,1
460,27,2,0,10,0,1,0.000,0,0,0.285111,...,0,0,0,0,0,0,0,0,0,1
461,22,3,0,9,0,1,0.000,0,0,0.285111,...,0,0,0,1,0,0,0,0,0,1
462,29,64,58,2059,322,716,0.450,98,268,0.365672,...,0,0,0,0,0,0,0,0,0,1
463,22,78,15,1820,206,482,0.427,26,99,0.262626,...,0,0,0,0,0,0,1,0,0,1
464,24,67,2,1157,140,337,0.415,37,125,0.296000,...,1,0,0,0,0,0,0,0,0,1
465,27,60,7,1445,197,493,0.400,79,231,0.341991,...,0,0,0,0,0,0,0,0,0,1
466,27,66,50,1674,231,526,0.439,84,234,0.358974,...,0,0,0,0,0,0,0,1,0,1
467,31,74,0,1834,280,672,0.417,83,225,0.368889,...,0,0,1,0,0,0,0,0,0,1
468,27,3,0,17,5,9,0.556,1,3,0.333333,...,0,0,0,0,0,0,0,0,0,1
469,27,36,13,751,73,192,0.380,42,129,0.325581,...,0,0,0,0,0,0,0,0,0,1
470,23,58,4,684,69,129,0.535,0,1,0.000000,...,0,0,0,0,0,0,0,0,0,1
471,22,58,31,1309,170,389,0.437,18,62,0.290323,...,0,0,0,0,0,0,0,0,0,1
472,34,29,1,388,56,141,0.397,17,54,0.314815,...,0,0,0,0,0,0,0,0,0,1
473,26,58,0,1077,224,331,0.677,0,0,0.285111,...,0,0,0,0,0,0,0,0,0,1
474,25,8,0,126,21,35,0.600,0,1,0.000000,...,0,0,0,0,0,0,0,0,0,1
475,28,68,13,984,111,297,0.374,69,202,0.341584,...,0,0,1,0,0,0,0,0,0,1
476,20,72,16,1765,345,808,0.427,40,188,0.212766,...,1,0,0,0,0,0,0,0,0,1
477,28,64,9,1810,387,889,0.435,135,350,0.385714,...,0,0,0,0,0,0,0,0,0,1
478,25,79,78,2718,582,1283,0.454,90,292,0.308219,...,1,0,0,0,0,0,0,0,0,1
479,21,82,3,1416,172,404,0.426,0,1,0.000000,...,0,0,0,0,0,0,0,0,0,1
480,24,70,9,1049,156,290,0.538,0,1,0.000000,...,0,0,0,0,0,0,0,0,0,1

In [75]:
X_train, X_test, y_train, y_test = train_test_split(
 X, Y, test_size = 0.3, random_state = 100)

In [70]:
import statsmodels.api as sm

C:\Users\vishal sangwan\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [76]:
linear_regression = sm.OLS(y_train,X_train)

In [77]:
result = linear_regression.fit()

In [78]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    pts   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 1.928e+30
Date:                Thu, 13 Sep 2018   Prob (F-statistic):               0.00
Time:                        15:28:29   Log-Likelihood:                 8902.8
No. Observations:                 336   AIC:                        -1.769e+04
Df Residuals:                     277   BIC:                        -1.746e+04
Df Model:                          58
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
age               1.199e-14   1.23e-14      0.972      0.332   -1.23e-14    3.63e-14
g                -2.687e-14   5.62e-15     -4.778      0.000   -3.79e-14   -1.58e-14
gs                3.553e-15   3.98e-15      0.892      0.373   -4.29e-15    1.14e-14
mp                2.109e-15   3.71e-16      5.687      0.000    1.38e-15    2.84e-15
fg                   1.6667   2.93e-15   5.68e+14      0.000       1.667       1.667
fga              -3.775e-15   1.24e-15     -3.049      0.003   -6.21e-15   -1.34e-15
fg.              -1.592e-12   2.51e-12     -0.634      0.527   -6.54e-12    3.35e-12
x3p                  1.3333   6.09e-15   2.19e+14      0.000       1.333       1.333
x3pa             -3.886e-15   2.47e-15     -1.571      0.117   -8.76e-15    9.85e-16
x3p.             -4.547e-13   5.23e-13     -0.870      0.385   -1.48e-12    5.75e-13
x2p                  0.3333      4e-15   8.33e+13      0.000       0.333       0.333
x2pa               2.22e-16   1.75e-15      0.127      0.899   -3.22e-15    3.67e-15
x2p.              1.705e-13   1.08e-12      0.158      0.874   -1.95e-12    2.29e-12
efg.              1.592e-12   2.36e-12      0.673      0.501   -3.06e-12    6.25e-12
ft                   1.0000   4.21e-15   2.37e+14      0.000       1.000       1.000
fta               1.776e-15   3.46e-15      0.514      0.608   -5.03e-15    8.58e-15
ft.               -1.35e-13   3.72e-13     -0.362      0.717   -8.68e-13    5.98e-13
orb              -4.607e-15   1.69e-15     -2.721      0.007   -7.94e-15   -1.27e-15
drb               5.218e-15   1.24e-15      4.192      0.000    2.77e-15    7.67e-15
trb              -3.275e-15   7.17e-16     -4.571      0.000   -4.69e-15   -1.86e-15
ast               5.274e-16    1.1e-15      0.480      0.632   -1.64e-15    2.69e-15
stl              -1.998e-15   3.17e-15     -0.630      0.529   -8.25e-15    4.25e-15
blk                2.22e-15   2.82e-15      0.787      0.432   -3.33e-15    7.77e-15
tov              -2.054e-15   3.35e-15     -0.614      0.540   -8.64e-15    4.53e-15
pf               -3.719e-15   2.26e-15     -1.649      0.100   -8.16e-15    7.22e-16
pos_C             3.553e-14    2.3e-13      0.154      0.877   -4.17e-13    4.88e-13
pos_F             3.126e-13   7.97e-13      0.392      0.695   -1.26e-12    1.88e-12
pos_G            -3.126e-13   8.11e-13     -0.386      0.700   -1.91e-12    1.28e-12
pos_PF                    0   2.19e-13          0      1.000   -4.31e-13    4.31e-13
pos_PG            1.528e-13   2.23e-13      0.685      0.494   -2.86e-13    5.92e-13
pos_SF           -4.263e-14   2.11e-13     -0.202      0.840   -4.59e-13    3.74e-13
pos_SG           -5.684e-14   2.06e-13     -0.276      0.783   -4.62e-13    3.48e-13
bref_team_id_ATL -3.411e-13   2.44e-13     -1.400      0.163   -8.21e-13    1.39e-13
bref_team_id_BOS -7.105e-15   2.49e-13     -0.029      0.977   -4.97e-13    4.83e-13
bref_team_id_BRK  1.421e-13   2.75e-13      0.517      0.605   -3.99e-13    6.83e-13
bref_team_id_CHA -5.684e-14   2.68e-13     -0.212      0.832   -5.84e-13    4.71e-13
bref_team_id_CHI -4.263e-14   2.85e-13     -0.149      0.881   -6.04e-13    5.19e-13
bref_team_id_CLE -1.421e-13   2.26e-13     -0.630      0.529   -5.86e-13    3.02e-13
bref_team_id_DAL  3.126e-13   2.61e-13      1.200      0.231      -2e-13    8.26e-13
bref_team_id_DEN -1.421e-13   3.18e-13     -0.447      0.655   -7.68e-13    4.84e-13
bref_team_id_DET -1.279e-13   2.85e-13     -0.449      0.654   -6.89e-13    4.33e-13
bref_team_id_GSW   1.99e-13   3.47e-13      0.573      0.567   -4.85e-13    8.83e-13
bref_team_id_HOU -1.421e-14   2.85e-13     -0.050      0.960   -5.75e-13    5.47e-13
bref_team_id_IND -5.684e-14   3.19e-13     -0.178      0.859   -6.85e-13    5.72e-13
bref_team_id_LAC   1.99e-13   2.78e-13      0.716      0.475   -3.48e-13    7.46e-13
bref_team_id_LAL -1.421e-13   2.84e-13     -0.500      0.617   -7.01e-13    4.17e-13
bref_team_id_MEM  5.684e-14   2.71e-13      0.210      0.834   -4.77e-13     5.9e-13
bref_team_id_MIA  7.105e-14   2.58e-13      0.275      0.783   -4.37e-13    5.79e-13
bref_team_id_MIL  5.684e-14   2.97e-13      0.191      0.848   -5.28e-13    6.41e-13
bref_team_id_MIN  5.684e-14   2.77e-13      0.205      0.838   -4.89e-13    6.02e-13
bref_team_id_NOP  2.736e-13   2.44e-13      1.119      0.264   -2.08e-13    7.55e-13
bref_team_id_NYK -1.137e-13   2.83e-13     -0.402      0.688    -6.7e-13    4.42e-13
bref_team_id_OKC  1.705e-13   2.68e-13      0.637      0.525   -3.57e-13    6.98e-13
bref_team_id_ORL -2.842e-14   2.79e-13     -0.102      0.919   -5.78e-13    5.21e-13
bref_team_id_PHI  3.553e-14   2.55e-13      0.139      0.889   -4.66e-13    5.37e-13
bref_team_id_PHO  2.061e-13   2.54e-13      0.810      0.419   -2.95e-13    7.07e-13
bref_team_id_POR  1.137e-13   2.84e-13      0.400      0.689   -4.46e-13    6.73e-13
bref_team_id_SAC  4.263e-14   3.18e-13      0.134      0.893   -5.83e-13    6.69e-13
bref_team_id_SAS  5.684e-14   3.29e-13      0.173      0.863    -5.9e-13    7.04e-13
bref_team_id_TOR  2.416e-13   3.25e-13      0.743      0.458   -3.98e-13    8.82e-13
bref_team_id_TOT -4.263e-14   1.36e-13     -0.313      0.755   -3.11e-13    2.26e-13
bref_team_id_UTA -2.558e-13    2.4e-13     -1.064      0.288   -7.29e-13    2.17e-13
bref_team_id_WAS  1.279e-13   2.95e-13      0.434      0.665   -4.52e-13    7.08e-13
intercept         2.274e-13   4.47e-13      0.508      0.612   -6.53e-13    1.11e-12
==============================================================================
Omnibus:                       45.542   Durbin-Watson:                   1.682
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               74.030
Skew:                          -0.815   Prob(JB):                     8.41e-17
Kurtosis:                       4.622   Cond. No.                     1.28e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.35e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [83]:
result.predict(X_test)

175    5.110000e+02
406    4.830000e+02
331    1.780000e+02
29     1.500000e+02
398    3.800000e+01
419    1.380000e+02
169    9.900000e+01
241    9.700000e+01
166    6.000000e+00
103    3.300000e+01
191    7.300000e+01
417    1.070000e+02
442    9.900000e+01
108    2.600000e+01
335    4.290000e+02
171    1.068000e+03
236    3.840000e+02
259    6.650000e+02
342    4.080000e+02
430    7.030000e+02
206    4.700000e+01
197    1.248000e+03
265    1.257000e+03
97     9.110000e+02
461    2.340043e-13
174    6.180000e+02
344    1.134000e+03
351    2.089268e-14
178    2.730000e+02
152    2.730000e+02
           ...
96     2.500000e+01
33     6.250000e+02
51     8.210000e+02
271    2.000000e+00
1      2.650000e+02
341    3.430000e+02
384    7.670000e+02
326    5.480000e+02
21     2.500000e+01
160    1.457000e+03
19     3.520000e+02
203    7.540000e+02
37     1.070000e+03
217    6.180000e+02
124    7.170000e+02
298    1.209000e+03
470    1.900000e+02
452    2.980000e+02
439    2.000000e+02
75     1.360000e+02
474    4.800000e+01
84     9.670000e+02
297    6.610000e+02
475    3.430000e+02
255    5.140000e+02
387    1.021000e+03
456    2.000000e+00
157    2.480000e+02
64     6.450000e+02
5      9.200000e+01
Length: 145, dtype: float64